### ISSUE TITLE
Error! Please help!

### ISSUE THREAD

**Issue by UjjwalGupta-Git** [TheThinMatrix/OpenGL-Tutorial-1#1]
Copied your code but got his error:

`Exception in thread "main" java.lang.NoClassDefFoundError: org/lwjgl/LWJGLException
	at engineTester.MainGameLoop.main(MainGameLoop.java:12)
Caused by: java.lang.ClassNotFoundException: org.lwjgl.LWJGLException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 1 more
`

I also tried adding the main method in DisplayManager.class for debugging purposes but got this:

`Error: Unable to initialize main class renderEngine.DisplayManager
Caused by: java.lang.NoClassDefFoundError: org/lwjgl/LWJGLException
`

**Comment by abhay7dev** [comment]
@UjjwalGupta-Git, which version of LWJGL are you using? It seems it is a `NoClassDefFoundError` which means that you might be using the wrong version of LWJGL or you might have added the libs incorrectly. watch [this](https://www.youtube.com/watch?v=Jdkq-aSFEA0) tutorial and make sure you are listening to what TheThinMatrix said. Your folder/package directory may also be causing this. I have not tried it yet myself though which means I may be wrong. Also, refer to [this](https://stackoverflow.com/questions/34413/why-am-i-getting-a-noclassdeffounderror-in-java) stackoverflow post and make sure your ide or text editor is configuring the build time and runtime classpaths correctly. The runtime classpath is most likely what is causing the error.

**Comment by UjjwalGupta-Git** [comment]
The link in the description of your unlisted video led me to a page that automatically downloads LWJGL-2.9.1.zip

**Comment by abhay7dev** [comment]
ok, once you downloaded that, did you add the jars the zip provided?

**Comment by UjjwalGupta-Git** [comment]
Yes

**Comment by abhay7dev** [comment]
Then I am not sure, sorry.

**Comment by UjjwalGupta-Git** [comment]
No worries I will figure it out somehow, I always do.🙂

**Comment by Piras314** [comment]
For future readers: I had this issue as well, you have to put your jars under "Classpath" instead of "Modulepath"

**Comment by Tanu257** [comment]
@CMDR-Piboy314  but then i can not access classes

**Comment by Piras314** [comment]
@Tanu257 oh? It worked just fine for me...

**Comment by Tanu257** [comment]
> @Tanu257 oh? It worked just fine for me...

Yeah , i was using jdk 18 instead of 1.8 as thin metrix showed
